#!/usr/bin/env bash

auth_version=$1
if [[ -z "$auth_version" ]]; then
    echo "You must supply a version number."
    exit 1
fi

# The single quotes around EOF is to stop attempted variable and backtick expansion.
read -r -d '' release_description << 'EOF'
SAFE Network client side Rust module(s)

EOF

echo "$release_description"
